import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import { Header } from "../components/Header";
import Feed from "../components/Feed";
import { UploadPost } from "../components/UploadPost";

const Home: NextPage = () => {
  const [open, setOpen] = useState<boolean>(false);

  return (
    <div className="h-screen overflow-y-scroll bg-gray-50">
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setOpen={setOpen} />
      <Feed />
      <UploadPost open={open} setOpen={setOpen} />
    </div>
  );
};

export default Home;
