import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "antd";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Button size="large" type="primary">
          Button
        </Button>
      </main>
    </div>
  );
};

export default Home;
