import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import Feed from "../components/Feed";

const Home: NextPage = () => {
  return (
    <div className="h-screen overflow-y-scroll bg-gray-50">
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Feed />
    </div>
  );
};

export default Home;
